### ISSUE TITLE
Secure Issue 49291: Expanding the wnprc billing module

### ISSUE THREAD

**Issue by labkey-bpatel** [LabKey/wnprc-modules#528]
Issue [49291](https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=49291)
[Spec](https://docs.google.com/document/d/1EVDGq8_ydHScxmwrZRqXBo4JtoljKl3dO99ENQMnwPA/edit#heading=h.bcr61ba681l)
Implementation on a 23.11 release

### Tasks
- [x] Investigate and scope out the details 
- [x] Investigate backwards compatibility
- [x] Q&As with client
- [x] Create a query for procedure charge id associations
- [x] Spec & Implementation plan
- [x] Implementation review @labkey-jeckels @ankurjuneja @labkey-martyp 
- [x] Schema updates - 1 hr
- [x] Calculate costs - 2 hrs
- [x] Refactor existing procedure query - 2 hrs
- [x] Process queries - 5 hrs
- [x] Test regression fixes - 3 hrs
- [x] Test updates - 3 hrs  
- [x] Validation - 2 hrs 
- [x] Refactor email notification - 2 hrs
- [x] Code Review - 1 hr @ankurjuneja @labkey-jeckels 
- [x] Code Review changes
- [x] TC Verify and merge 📌
